name = "uber-pokja"
account_id = "cdcd2c8177520b10e161f95fb0e12220"
workers_dev = true
compatibility_date = "2026-09-25"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
