<script>
	import { onMount } from 'svelte';
	import { Button, Card, Input, Select, showToast, Switch } from '@khwarizmi/svelte-ui';
	import { Bell, ChevronLeft, ChevronRight, LockKeyhole, MapPin, PackageCheck, Pencil, ShieldCheck, UserRound } from 'lucide-svelte';

	let profil = $state({ nama: '', hp: '', alamat: '', rtRw: '', kelurahan: '', kecamatan: '', kota: '', provinsi: '', kodePos: '', email: '', gender: '', lahir: '', notifPromo: true, notifPesanan: true });
	let editData = $state(false);
	let editAlamat = $state(false);
	const inisial = $derived(profil.nama.trim().split(/\s+/).filter(Boolean).slice(0, 2).map((n) => n[0]).join('').toUpperCase() || 'UM');
	const alamatTampil = $derived([profil.alamat, profil.rtRw && `RT/RW ${profil.rtRw}`, profil.kelurahan, profil.kecamatan, profil.kota, profil.provinsi, profil.kodePos].filter(Boolean).join(', '));
	onMount(() => { try { profil = { ...profil, ...JSON.parse(localStorage.getItem('uber-pokja:marketplace:buyer') ?? '{}') }; } catch {} });
	function simpan() { localStorage.setItem('uber-pokja:marketplace:buyer', JSON.stringify(profil)); showToast({ tone: 'success', title: 'Profil disimpan', description: 'Identitas dan alamat utama diperbarui.' }); }
	function segera(label) { showToast({ tone: 'info', title: label, description: 'Fitur ini akan terhubung ke autentikasi akun saat backend aktif.' }); }
</script>

<svelte:head><title>Profil · UBER Market</title></svelte:head>

<main class="min-h-dvh bg-[#faf9f5] px-4 py-5 text-slate-800 sm:px-6"><div class="mx-auto max-w-2xl">
	<a href="/marketplace" class="inline-flex items-center gap-1.5 text-sm font-black text-primary-700"><ChevronLeft size={18} /> Kembali ke beranda</a>
	<section class="mt-6 overflow-hidden rounded-3xl bg-linear-to-br from-primary-900 to-primary-700 p-5 text-white shadow-sm sm:p-6"><div class="flex items-center gap-4"><span class="grid size-16 place-items-center rounded-3xl bg-white/15 text-xl font-black ring-1 ring-white/20">{inisial}</span><div class="min-w-0 flex-1"><h1 class="truncate text-xl font-black">{profil.nama || 'Customer UBER Market'}</h1><p class="mt-1 truncate text-sm font-medium text-primary-100">{profil.email || 'Lengkapi email Anda'}</p></div><Button variant="outline" size="sm" class="profile-edit-button shrink-0 !border-white/30 !bg-white/10 !text-white !shadow-[0_3px_0_0_rgb(255_255_255_/_0.28)] hover:!translate-y-px hover:!bg-white/10 hover:!shadow-[0_2px_0_0_rgb(255_255_255_/_0.28)]" onclick={() => { editData = true; document.getElementById('data-pribadi')?.scrollIntoView({ behavior: 'smooth' }); }}>Edit</Button></div><div class="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-2xl bg-white/15 text-center"><a href="/marketplace/pesanan" class="bg-primary-800/40 px-3 py-3 text-sm font-bold hover:bg-white/10"><strong class="block text-lg">Pesanan</strong><span class="text-xs text-primary-100">Lihat status belanja</span></a><a href="/marketplace/notifikasi" class="bg-primary-800/40 px-3 py-3 text-sm font-bold hover:bg-white/10"><strong class="block text-lg">Info</strong><span class="text-xs text-primary-100">Promo & notifikasi</span></a></div></section>
	<Card id="data-pribadi" padding="lg" class="mt-5"><div class="flex items-center justify-between gap-3"><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-xl bg-primary-50 text-primary-700"><UserRound size={19} /></span><div><h2 class="font-black">Data pribadi</h2><p class="text-sm font-medium text-slate-500">Digunakan untuk identitas customer.</p></div></div><Button variant="outline" size="sm" class="!border-primary-200 !bg-primary-50 !text-primary-800 !shadow-[0_2px_0_0_var(--primary-200)] hover:!translate-y-px hover:!bg-primary-50 hover:!shadow-[0_1px_0_0_var(--primary-200)] active:!translate-y-[2px] active:!shadow-none" onclick={() => (editData = !editData)}><Pencil size={15} /> {editData ? 'Tutup' : 'Edit'}</Button></div>
		{#if editData}<div class="mt-5 grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><Input label="Nama lengkap" placeholder="Nama lengkap" bind:value={profil.nama} /></div><Input label="Nomor WhatsApp" inputmode="tel" placeholder="08xx-xxxx-xxxx" bind:value={profil.hp} /><Input label="Email" inputmode="email" placeholder="nama@email.com" bind:value={profil.email} /><Select label="Jenis kelamin" options={[{ value: '', label: 'Pilih jika ingin diisi' }, { value: 'Perempuan', label: 'Perempuan' }, { value: 'Laki-laki', label: 'Laki-laki' }, { value: 'Lainnya', label: 'Lainnya' }]} bind:value={profil.gender} /><label class="block text-sm font-bold text-slate-700">Tanggal lahir<input class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-primary-500 focus:ring-4 focus:ring-primary-100" type="date" bind:value={profil.lahir} /></label></div>{:else}<div class="mt-5 grid grid-cols-2 gap-x-5 gap-y-4 rounded-2xl bg-slate-50 p-4 text-sm"><div><p class="text-xs font-bold text-slate-400">Nama</p><p class="mt-1 font-black">{profil.nama || 'Belum diisi'}</p></div><div><p class="text-xs font-bold text-slate-400">WhatsApp</p><p class="mt-1 font-black">{profil.hp || 'Belum diisi'}</p></div><div><p class="text-xs font-bold text-slate-400">Email</p><p class="mt-1 font-black">{profil.email || 'Belum diisi'}</p></div><div><p class="text-xs font-bold text-slate-400">Jenis kelamin</p><p class="mt-1 font-black">{profil.gender || 'Belum diisi'}</p></div></div>{/if}
	</Card>
	<Card padding="lg" class="mt-5"><div class="flex items-center justify-between gap-3"><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-xl bg-primary-50 text-primary-700"><MapPin size={19} /></span><div><h2 class="font-black">Alamat saya</h2><p class="text-sm font-medium text-slate-500">Alamat utama untuk pengiriman.</p></div></div><a href="/marketplace/alamat" class="inline-flex items-center justify-center gap-2 rounded-2xl border px-3 py-1.5 text-xs font-black transition-all duration-150 !border-primary-200 !bg-primary-50 !text-primary-800 !shadow-[0_2px_0_0_var(--primary-200)] hover:translate-y-px hover:!bg-primary-50 hover:!shadow-[0_1px_0_0_var(--primary-200)] active:translate-y-[2px] active:shadow-none"><Pencil size={15} /> Kelola</a></div><div class="mt-4 rounded-2xl bg-slate-50 p-4"><p class="font-black">{profil.nama || 'Nama penerima'} <span class="font-medium text-slate-500">· {profil.hp || 'Nomor WhatsApp'}</span></p><p class="mt-2 text-sm leading-6 font-medium text-slate-600">{alamatTampil || 'Belum ada alamat utama. Tambahkan alamat agar checkout lebih cepat.'}</p><a href="/marketplace/alamat" class="mt-3 inline-flex text-sm font-black text-primary-700">Kelola beberapa alamat →</a></div></Card>
	<Card padding="none" class="mt-5 overflow-hidden"><div class="px-5 py-4"><h2 class="font-black">Akun & pengaturan</h2></div><a href="/marketplace/pesanan" class="profile-row"><PackageCheck size={19} /><span>Pesanan saya</span><ChevronRight size={18} /></a><a href="/marketplace/notifikasi" class="profile-row"><Bell size={19} /><span>Notifikasi</span><ChevronRight size={18} /></a><button class="profile-row w-full" onclick={() => segera('Keamanan akun')}><LockKeyhole size={19} /><span>Keamanan akun</span><ChevronRight size={18} /></button><button class="profile-row w-full" onclick={() => segera('Privasi akun')}><ShieldCheck size={19} /><span>Privasi & bantuan</span><ChevronRight size={18} /></button></Card>
	<Card padding="lg" class="mt-5"><h2 class="font-black">Preferensi notifikasi</h2><div class="mt-4 space-y-3"><Switch bind:checked={profil.notifPesanan} card label="Status pesanan" description="Pembayaran, proses Gudang, dan pengiriman." /><Switch bind:checked={profil.notifPromo} card label="Promo UBER Market" description="Paket hemat dan produk pilihan." /></div></Card>
	<Button fullWidth size="lg" class="mt-6 mb-8 !bg-none !bg-brand-600 !shadow-[0_4px_0_0_#0b432c] hover:!translate-y-[2px] hover:!shadow-[0_2px_0_0_#0b432c] active:!translate-y-[4px] active:!shadow-none" onclick={simpan}>Simpan perubahan</Button>
</div></main>

<style>
	:global(.profile-edit-button:active) { transform: translateY(2px) !important; box-shadow: 0 1px 0 rgb(255 255 255 / 0.28) !important; }
	.profile-row { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center; gap: 0.8rem; border-top: 1px solid #f1f5f9; padding: 1rem 1.25rem; color: #526174; font-size: 0.9rem; font-weight: 800; text-align: left; transition: background-color 160ms ease, color 160ms ease; }
	.profile-row:hover { background: #f7fbf8; color: #0f6a42; }
</style>
